volumes:
  ckan_storage:
  pg_data:
  solr_data:
  pip_cache:
  site_packages:
  vscode_server:

services:

  ckan-dev:
    user: ckan:ckan
    build:
      context: ckan/
      dockerfile: Dockerfile.dev
      args:
        - TZ=${TZ}
      platforms:
        - linux/amd64
    image: ${COMPOSE_PROJECT_NAME}-ckan-dev
    platform: linux/amd64
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "0.0.0.0:${CKAN_PORT_HOST}:5000"
    volumes:
      - ckan_storage:/var/lib/ckan
      - ./src:/srv/app/src_extensions
      - pip_cache:/root/.cache/pip
      - site_packages:/usr/lib/python3.10/site-packages
      - vscode_server:/root/.vscode-server
      - ./ckan/config:/srv/app/config
      - ./logs:/srv/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:5000"]

  ckan-dev-worker:
    user: ckan:ckan
    build:
      context: ckan/
      dockerfile: Dockerfile.worker
      args:
        - TZ=${TZ}
        - CKAN_IMAGE=${COMPOSE_PROJECT_NAME}-ckan-dev
      platforms:
        - linux/amd64
    platform: linux/amd64
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy
      ckan-dev:
        condition: service_started
    volumes:
      - ckan_storage:/var/lib/ckan
      - ./src:/srv/app/src_extensions
      - pip_cache:/root/.cache/pip
      - site_packages:/usr/lib/python3.10/site-packages
      - vscode_server:/root/.vscode-server
      - ./logs:/srv/app/logs
      - ./spatial_data:/srv/app/spatial_data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "supervisorctl", "status"]

  db:
    build:
      context: postgresql/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - CKAN_DB_USER
      - CKAN_DB_PASSWORD
      - CKAN_DB
      - DATASTORE_READONLY_USER
      - DATASTORE_READONLY_PASSWORD
      - DATASTORE_DB
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
    ports:
      - :5432
     
  solr:
    image: ckan/ckan-solr:${SOLR_IMAGE_VERSION}
    platform: linux/amd64
    volumes:
      - solr_data:/var/solr
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8983/solr/"]
    ports:
      - :8983

  redis:
    image: redis:${REDIS_VERSION}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]
